// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/service/career/cv (interfaces: ClipboardWriter)

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClipboardWriter is a mock of ClipboardWriter interface.
type MockClipboardWriter struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardWriterMockRecorder
}

// MockClipboardWriterMockRecorder is the mock recorder for MockClipboardWriter.
type MockClipboardWriterMockRecorder struct {
	mock *MockClipboardWriter
}

// NewMockClipboardWriter creates a new mock instance.
func NewMockClipboardWriter(ctrl *gomock.Controller) *MockClipboardWriter {
	mock := &MockClipboardWriter{ctrl: ctrl}
	mock.recorder = &MockClipboardWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboardWriter) EXPECT() *MockClipboardWriterMockRecorder {
	return m.recorder
}

// IsUnsupported mocks base method.
func (m *MockClipboardWriter) IsUnsupported() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUnsupported")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUnsupported indicates an expected call of IsUnsupported.
func (mr *MockClipboardWriterMockRecorder) IsUnsupported() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUnsupported", reflect.TypeOf((*MockClipboardWriter)(nil).IsUnsupported))
}

// WriteAll mocks base method.
func (m *MockClipboardWriter) WriteAll(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAll", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAll indicates an expected call of WriteAll.
func (mr *MockClipboardWriterMockRecorder) WriteAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAll", reflect.TypeOf((*MockClipboardWriter)(nil).WriteAll), arg0)
}
