// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/service/career/cv (interfaces: CVGenerationService)

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	career "github.com/baphled/kariya/internal/domain/career"
	gomock "github.com/golang/mock/gomock"
)

// MockCVGenerationService is a mock of CVGenerationService interface.
type MockCVGenerationService struct {
	ctrl     *gomock.Controller
	recorder *MockCVGenerationServiceMockRecorder
}

// MockCVGenerationServiceMockRecorder is the mock recorder for MockCVGenerationService.
type MockCVGenerationServiceMockRecorder struct {
	mock *MockCVGenerationService
}

// NewMockCVGenerationService creates a new mock instance.
func NewMockCVGenerationService(ctrl *gomock.Controller) *MockCVGenerationService {
	mock := &MockCVGenerationService{ctrl: ctrl}
	mock.recorder = &MockCVGenerationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCVGenerationService) EXPECT() *MockCVGenerationServiceMockRecorder {
	return m.recorder
}

// GenerateCV mocks base method.
func (m *MockCVGenerationService) GenerateCV(arg0 context.Context, arg1 string) (*career.CVView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCV", arg0, arg1)
	ret0, _ := ret[0].(*career.CVView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCV indicates an expected call of GenerateCV.
func (mr *MockCVGenerationServiceMockRecorder) GenerateCV(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCV", reflect.TypeOf((*MockCVGenerationService)(nil).GenerateCV), arg0, arg1)
}

// GenerateCVFromConfig mocks base method.
func (m *MockCVGenerationService) GenerateCVFromConfig(arg0 context.Context, arg1 *career.CVConfig) (*career.CVView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCVFromConfig", arg0, arg1)
	ret0, _ := ret[0].(*career.CVView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCVFromConfig indicates an expected call of GenerateCVFromConfig.
func (mr *MockCVGenerationServiceMockRecorder) GenerateCVFromConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCVFromConfig", reflect.TypeOf((*MockCVGenerationService)(nil).GenerateCVFromConfig), arg0, arg1)
}
