// Package mocksvc provides GoMock-generated test doubles for service interfaces.
//
// # Overview
//
// All mocks in this package are auto-generated by mockgen from interfaces
// defined in internal/service/career/. Do not edit generated files manually.
//
// # Generation
//
// Regenerate all mocks:
//
//	make generate-mocks
//
// Or generate only service mocks:
//
//	go generate ./internal/service/career/...
//
// # Usage
//
//	import mocksvc "github.com/baphled/kariya/internal/testutil/mocks/service"
//
//	ctrl := gomock.NewController(t)
//	mockSvc := mocksvc.NewMockCVGenerationService(ctrl)
//	mockSvc.EXPECT().GenerateCV(gomock.Any(), gomock.Eq("default")).Return(testCV, nil)
package mocksvc
