// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/service/career/skillinference (interfaces: SkillInferenceService)

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	career "github.com/baphled/kariya/internal/domain/career"
	skillinference "github.com/baphled/kariya/internal/service/career/skillinference"
	gomock "github.com/golang/mock/gomock"
)

// MockSkillInferenceService is a mock of SkillInferenceService interface.
type MockSkillInferenceService struct {
	ctrl     *gomock.Controller
	recorder *MockSkillInferenceServiceMockRecorder
}

// MockSkillInferenceServiceMockRecorder is the mock recorder for MockSkillInferenceService.
type MockSkillInferenceServiceMockRecorder struct {
	mock *MockSkillInferenceService
}

// NewMockSkillInferenceService creates a new mock instance.
func NewMockSkillInferenceService(ctrl *gomock.Controller) *MockSkillInferenceService {
	mock := &MockSkillInferenceService{ctrl: ctrl}
	mock.recorder = &MockSkillInferenceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillInferenceService) EXPECT() *MockSkillInferenceServiceMockRecorder {
	return m.recorder
}

// CreateSkillsFromSuggestions mocks base method.
func (m *MockSkillInferenceService) CreateSkillsFromSuggestions(arg0 context.Context, arg1 []skillinference.SkillSuggestion) ([]*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSkillsFromSuggestions", arg0, arg1)
	ret0, _ := ret[0].([]*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSkillsFromSuggestions indicates an expected call of CreateSkillsFromSuggestions.
func (mr *MockSkillInferenceServiceMockRecorder) CreateSkillsFromSuggestions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSkillsFromSuggestions", reflect.TypeOf((*MockSkillInferenceService)(nil).CreateSkillsFromSuggestions), arg0, arg1)
}

// InferSkillsFromBurst mocks base method.
func (m *MockSkillInferenceService) InferSkillsFromBurst(arg0 context.Context, arg1 *career.Burst, arg2 []*career.Event) (*skillinference.InferenceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InferSkillsFromBurst", arg0, arg1, arg2)
	ret0, _ := ret[0].(*skillinference.InferenceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InferSkillsFromBurst indicates an expected call of InferSkillsFromBurst.
func (mr *MockSkillInferenceServiceMockRecorder) InferSkillsFromBurst(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InferSkillsFromBurst", reflect.TypeOf((*MockSkillInferenceService)(nil).InferSkillsFromBurst), arg0, arg1, arg2)
}

// InferSkillsFromEvents mocks base method.
func (m *MockSkillInferenceService) InferSkillsFromEvents(arg0 context.Context, arg1 []*career.Event) (*skillinference.InferenceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InferSkillsFromEvents", arg0, arg1)
	ret0, _ := ret[0].(*skillinference.InferenceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InferSkillsFromEvents indicates an expected call of InferSkillsFromEvents.
func (mr *MockSkillInferenceServiceMockRecorder) InferSkillsFromEvents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InferSkillsFromEvents", reflect.TypeOf((*MockSkillInferenceService)(nil).InferSkillsFromEvents), arg0, arg1)
}
