// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/repository/career (interfaces: BurstRepository)

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	career "github.com/baphled/kariya/internal/domain/career"
	career0 "github.com/baphled/kariya/internal/repository/career"
	gomock "github.com/golang/mock/gomock"
)

// MockBurstRepository is a mock of BurstRepository interface.
type MockBurstRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBurstRepositoryMockRecorder
}

// MockBurstRepositoryMockRecorder is the mock recorder for MockBurstRepository.
type MockBurstRepositoryMockRecorder struct {
	mock *MockBurstRepository
}

// NewMockBurstRepository creates a new mock instance.
func NewMockBurstRepository(ctrl *gomock.Controller) *MockBurstRepository {
	mock := &MockBurstRepository{ctrl: ctrl}
	mock.recorder = &MockBurstRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBurstRepository) EXPECT() *MockBurstRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockBurstRepository) Count(arg0 context.Context, arg1 career0.BurstListFilters) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockBurstRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockBurstRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockBurstRepository) Create(arg0 context.Context, arg1 *career.Burst) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBurstRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBurstRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockBurstRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBurstRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBurstRepository)(nil).Delete), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockBurstRepository) GetByID(arg0 context.Context, arg1 string) (*career.Burst, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*career.Burst)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBurstRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBurstRepository)(nil).GetByID), arg0, arg1)
}

// List mocks base method.
func (m *MockBurstRepository) List(arg0 context.Context, arg1 career0.BurstListFilters) ([]*career.Burst, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*career.Burst)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBurstRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBurstRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockBurstRepository) Update(arg0 context.Context, arg1 *career.Burst) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBurstRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBurstRepository)(nil).Update), arg0, arg1)
}
