// Package mockrepo provides GoMock-generated test doubles for repository interfaces.
//
// # Overview
//
// All mocks in this package are auto-generated by mockgen from interfaces
// defined in internal/repository/career/. Do not edit generated files manually.
//
// # Generation
//
// Regenerate all mocks:
//
//	make generate-mocks
//
// Or generate only repository mocks:
//
//	go generate ./internal/repository/career/...
//
// # Usage
//
//	import mockrepo "github.com/baphled/kariya/internal/testutil/mocks/repository"
//
//	ctrl := gomock.NewController(t)
//	mockRepo := mockrepo.NewMockEventRepository(ctrl)
//	mockRepo.EXPECT().GetByID(gomock.Any(), gomock.Eq("event-1")).Return(testEvent, nil)
package mockrepo
