// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/repository/career (interfaces: FactRepository)

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	career "github.com/baphled/kariya/internal/domain/career"
	career0 "github.com/baphled/kariya/internal/repository/career"
	gomock "github.com/golang/mock/gomock"
)

// MockFactRepository is a mock of FactRepository interface.
type MockFactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFactRepositoryMockRecorder
}

// MockFactRepositoryMockRecorder is the mock recorder for MockFactRepository.
type MockFactRepositoryMockRecorder struct {
	mock *MockFactRepository
}

// NewMockFactRepository creates a new mock instance.
func NewMockFactRepository(ctrl *gomock.Controller) *MockFactRepository {
	mock := &MockFactRepository{ctrl: ctrl}
	mock.recorder = &MockFactRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactRepository) EXPECT() *MockFactRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockFactRepository) Count(arg0 context.Context, arg1 career0.FactListFilters) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockFactRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockFactRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
func (m *MockFactRepository) Create(arg0 context.Context, arg1 *career.Fact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFactRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFactRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockFactRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFactRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFactRepository)(nil).Delete), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockFactRepository) GetByID(arg0 context.Context, arg1 string) (*career.Fact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*career.Fact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFactRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFactRepository)(nil).GetByID), arg0, arg1)
}

// GetBySourceBurstID mocks base method.
func (m *MockFactRepository) GetBySourceBurstID(arg0 context.Context, arg1 string) ([]*career.Fact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySourceBurstID", arg0, arg1)
	ret0, _ := ret[0].([]*career.Fact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySourceBurstID indicates an expected call of GetBySourceBurstID.
func (mr *MockFactRepositoryMockRecorder) GetBySourceBurstID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySourceBurstID", reflect.TypeOf((*MockFactRepository)(nil).GetBySourceBurstID), arg0, arg1)
}

// GetBySourceEventID mocks base method.
func (m *MockFactRepository) GetBySourceEventID(arg0 context.Context, arg1 string) ([]*career.Fact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySourceEventID", arg0, arg1)
	ret0, _ := ret[0].([]*career.Fact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySourceEventID indicates an expected call of GetBySourceEventID.
func (mr *MockFactRepositoryMockRecorder) GetBySourceEventID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySourceEventID", reflect.TypeOf((*MockFactRepository)(nil).GetBySourceEventID), arg0, arg1)
}

// List mocks base method.
func (m *MockFactRepository) List(arg0 context.Context, arg1 career0.FactListFilters) ([]*career.Fact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*career.Fact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFactRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFactRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockFactRepository) Update(arg0 context.Context, arg1 *career.Fact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFactRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFactRepository)(nil).Update), arg0, arg1)
}
