// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/repository/career (interfaces: SkillRepository)

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"
	time "time"

	career "github.com/baphled/kariya/internal/domain/career"
	career0 "github.com/baphled/kariya/internal/repository/career"
	gomock "github.com/golang/mock/gomock"
)

// MockSkillRepository is a mock of SkillRepository interface.
type MockSkillRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSkillRepositoryMockRecorder
}

// MockSkillRepositoryMockRecorder is the mock recorder for MockSkillRepository.
type MockSkillRepositoryMockRecorder struct {
	mock *MockSkillRepository
}

// NewMockSkillRepository creates a new mock instance.
func NewMockSkillRepository(ctrl *gomock.Controller) *MockSkillRepository {
	mock := &MockSkillRepository{ctrl: ctrl}
	mock.recorder = &MockSkillRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillRepository) EXPECT() *MockSkillRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSkillRepository) Create(arg0 context.Context, arg1 *career.Skill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSkillRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSkillRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockSkillRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSkillRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSkillRepository)(nil).Delete), arg0, arg1)
}

// GetByCategory mocks base method.
func (m *MockSkillRepository) GetByCategory(arg0 context.Context, arg1 string) ([]*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCategory", arg0, arg1)
	ret0, _ := ret[0].([]*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCategory indicates an expected call of GetByCategory.
func (mr *MockSkillRepositoryMockRecorder) GetByCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategory", reflect.TypeOf((*MockSkillRepository)(nil).GetByCategory), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockSkillRepository) GetByID(arg0 context.Context, arg1 string) (*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSkillRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSkillRepository)(nil).GetByID), arg0, arg1)
}

// GetByName mocks base method.
func (m *MockSkillRepository) GetByName(arg0 context.Context, arg1 string) (*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", arg0, arg1)
	ret0, _ := ret[0].(*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockSkillRepositoryMockRecorder) GetByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockSkillRepository)(nil).GetByName), arg0, arg1)
}

// GetEventCountsForSkills mocks base method.
func (m *MockSkillRepository) GetEventCountsForSkills(arg0 context.Context) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventCountsForSkills", arg0)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventCountsForSkills indicates an expected call of GetEventCountsForSkills.
func (mr *MockSkillRepositoryMockRecorder) GetEventCountsForSkills(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventCountsForSkills", reflect.TypeOf((*MockSkillRepository)(nil).GetEventCountsForSkills), arg0)
}

// GetEventsUsingSkill mocks base method.
func (m *MockSkillRepository) GetEventsUsingSkill(arg0 context.Context, arg1 string) ([]*career.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsUsingSkill", arg0, arg1)
	ret0, _ := ret[0].([]*career.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsUsingSkill indicates an expected call of GetEventsUsingSkill.
func (mr *MockSkillRepositoryMockRecorder) GetEventsUsingSkill(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsUsingSkill", reflect.TypeOf((*MockSkillRepository)(nil).GetEventsUsingSkill), arg0, arg1)
}

// GetLastUsedForSkills mocks base method.
func (m *MockSkillRepository) GetLastUsedForSkills(arg0 context.Context) (map[string]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastUsedForSkills", arg0)
	ret0, _ := ret[0].(map[string]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastUsedForSkills indicates an expected call of GetLastUsedForSkills.
func (mr *MockSkillRepositoryMockRecorder) GetLastUsedForSkills(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastUsedForSkills", reflect.TypeOf((*MockSkillRepository)(nil).GetLastUsedForSkills), arg0)
}

// GetSkillsForEvent mocks base method.
func (m *MockSkillRepository) GetSkillsForEvent(arg0 context.Context, arg1 string) ([]*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkillsForEvent", arg0, arg1)
	ret0, _ := ret[0].([]*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkillsForEvent indicates an expected call of GetSkillsForEvent.
func (mr *MockSkillRepositoryMockRecorder) GetSkillsForEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkillsForEvent", reflect.TypeOf((*MockSkillRepository)(nil).GetSkillsForEvent), arg0, arg1)
}

// List mocks base method.
func (m *MockSkillRepository) List(arg0 context.Context, arg1 *career0.SkillListFilters) ([]*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSkillRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSkillRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockSkillRepository) Update(arg0 context.Context, arg1 *career.Skill) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSkillRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSkillRepository)(nil).Update), arg0, arg1)
}
