package statematrix

import (
	"encoding/json"
	"os"
	"sort"
	"text/template"
	"time"
)

// GenerateMarkdown generates the STATE_MATRIX.md file
func GenerateMarkdown(matrix *StateMatrix, path string) error {
	// Ensure matrix has timestamp
	if matrix.GeneratedAt.IsZero() {
		matrix.GeneratedAt = time.Now()
	}

	// Sort intents and screens
	sort.Slice(matrix.Intents, func(i, j int) bool {
		return matrix.Intents[i].Name < matrix.Intents[j].Name
	})
	sort.Slice(matrix.Screens, func(i, j int) bool {
		return matrix.Screens[i].Name < matrix.Screens[j].Name
	})

	tmpl := `# KaRiya TUI State Matrix

> **Auto-generated**: Do not edit manually. Run ` + "`make generate-state-matrix`" + ` to update.  
> **Generated**: {{.GeneratedAt.Format "2006-01-02T15:04:05Z07:00"}}  
> **Source**: ` + "`cmd/generate-state-matrix/main.go`" + `

## Summary

| Metric | Value |
|--------|-------|
| Total Intents | {{.TotalIntents}} |
| Total Screens | {{.TotalScreens}} |
| Total States | {{.TotalStates}} |

## State Type Definitions

| Type | Description | Escape Behavior |
|------|-------------|-----------------|
| **ROOT** | Entry state of intent/screen | Cancel intent → Main Menu |
| **Intermediate** | Middle navigation state | Back → Previous state |
| **Confirmation** | User confirmation required | Cancel → Parent state |
| **Async** | Background operation | Varies (some block, some allow back) |
| **Modal** | Overlay editor/form | Close modal → Parent state |
| **Final** | Operation complete | Deactivate intent |
| **Error** | Operation failed | Deactivate (retry often available) |

## Intent States

{{if .Intents}}
{{range .Intents}}
### {{.Name}}

**File**: ` + "`{{.File}}`" + `  
**States**: {{.StateCount}}

| State | Type | Escape Behavior |
|-------|------|-----------------|
{{range .States}}| ` + "`{{.Constant}}`" + ` | {{.Type}} | {{.EscapeBehavior}} |
{{end}}

{{end}}
{{else}}
*No intent states found.*

{{end}}

## Screen States

{{if .Screens}}
{{range .Screens}}
### {{.Name}}

**File**: ` + "`{{.File}}`" + `  
**States**: {{.StateCount}}

| State | Type | Escape Behavior |
|-------|------|-----------------|
{{range .States}}| ` + "`{{.Constant}}`" + ` | {{.Type}} | {{.EscapeBehavior}} |
{{end}}

{{end}}
{{else}}
*No screen states found. Screens will appear here as intents are migrated to the new architecture.*

{{end}}

---

*Generated by ` + "`cmd/generate-state-matrix/main.go`" + `*
`

	t, err := template.New("matrix").Parse(tmpl)
	if err != nil {
		return err
	}

	// #nosec G304 - Path is safely constructed using filepath.Join from project root
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	return t.Execute(f, matrix)
}

// GenerateJSON generates the state_matrix.json file
func GenerateJSON(matrix *StateMatrix, path string) error {
	// Ensure matrix has timestamp
	if matrix.GeneratedAt.IsZero() {
		matrix.GeneratedAt = time.Now()
	}

	data, err := json.MarshalIndent(matrix, "", "  ")
	if err != nil {
		return err
	}

	// #nosec G306 - JSON file permissions are appropriate for generated documentation
	return os.WriteFile(path, data, 0600)
}
