// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/repository/career (interfaces: EventRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	career "github.com/baphled/kariya/internal/domain/career"
	career0 "github.com/baphled/kariya/internal/repository/career"
	gomock "github.com/golang/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
//
// Expected:
//   - controller must be valid.
//
// Returns:
//   - A fully initialized MockEventRepository ready for use.
//
// Side effects:
//   - None.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
//
// Returns:
//   - A fully initialized MockEventRepositoryMockRecorder ready for use.
//
// Side effects:
//   - None.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockEventRepository) Count(arg0 context.Context, arg1 career0.EventListFilters) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
//
// Expected:
//   - interface{} must be valid.
//
// Returns:
//   - A fully initialized gomock.Call ready for use.
//
// Side effects:
//   - None.
func (mr *MockEventRepositoryMockRecorder) Count(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockEventRepository)(nil).Count), arg0, arg1)
}

// Create mocks base method.
//
// Expected:
//   - event must be valid.
//
// Returns:
//   - A error value.
//
// Side effects:
//   - None.
func (m *MockEventRepository) Create(arg0 context.Context, arg1 *career.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
//
// Expected:
//   - interface{} must be valid.
//
// Returns:
//   - A fully initialized gomock.Call ready for use.
//
// Side effects:
//   - None.
func (mr *MockEventRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
//
// Expected:
//   - Must be a valid string.
//
// Returns:
//   - A error value.
//
// Side effects:
//   - None.
func (m *MockEventRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
//
// Expected:
//   - interface{} must be valid.
//
// Returns:
//   - A fully initialized gomock.Call ready for use.
//
// Side effects:
//   - None.
func (mr *MockEventRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventRepository)(nil).Delete), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockEventRepository) GetByID(arg0 context.Context, arg1 string) (*career.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*career.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
//
// Expected:
//   - interface{} must be valid.
//
// Returns:
//   - A fully initialized gomock.Call ready for use.
//
// Side effects:
//   - None.
func (mr *MockEventRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventRepository)(nil).GetByID), arg0, arg1)
}

// List mocks base method.
func (m *MockEventRepository) List(arg0 context.Context, arg1 career0.EventListFilters) ([]*career.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*career.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
//
// Expected:
//   - interface{} must be valid.
//
// Returns:
//   - A fully initialized gomock.Call ready for use.
//
// Side effects:
//   - None.
func (mr *MockEventRepositoryMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventRepository)(nil).List), arg0, arg1)
}

// Update mocks base method.
//
// Expected:
//   - event must be valid.
//
// Returns:
//   - A error value.
//
// Side effects:
//   - None.
func (m *MockEventRepository) Update(arg0 context.Context, arg1 *career.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
//
// Expected:
//   - interface{} must be valid.
//
// Returns:
//   - A fully initialized gomock.Call ready for use.
//
// Side effects:
//   - None.
func (mr *MockEventRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventRepository)(nil).Update), arg0, arg1)
}
