// Package mocks provides centralized GoMock-generated test doubles for all KaRiya interfaces.
//
// # Overview
//
// Mocks are organized by architectural layer:
//
//   - repository/ (mockrepo): Repository layer mocks (EventRepository, BurstRepository, etc.)
//   - service/ (mocksvc): Service layer mocks (CVGenerationService, ClipboardWriter, etc.)
//   - intent/ (mockintent): Intent layer mocks (BurstService, EventService, etc.)
//
// # Generation
//
// All mocks are auto-generated by mockgen via go:generate directives in source files.
// Regenerate all mocks with:
//
//	make generate-mocks
//
// # Import Patterns
//
//	import mockrepo "github.com/baphled/kariya/internal/testutil/mocks/repository"
//	import mocksvc "github.com/baphled/kariya/internal/testutil/mocks/service"
//	import mockintent "github.com/baphled/kariya/internal/testutil/mocks/intent"
//
// # Deprecated
//
// Hand-written mocks in this package (burst_service_mock.go) are deprecated
// and will be removed once all consumers migrate to the layer sub-packages.
package mocks
