// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/cli/intents/browsetimeline (interfaces: EventService)

// Package mockintent is a generated GoMock package.
package mockintent

import (
	context "context"
	reflect "reflect"
	time "time"

	service "github.com/baphled/kariya/internal/cli/service"
	career "github.com/baphled/kariya/internal/domain/career"
	career0 "github.com/baphled/kariya/internal/repository/career"
	career1 "github.com/baphled/kariya/internal/service/career"
	gomock "github.com/golang/mock/gomock"
)

// MockBrowseEventService is a mock of EventService interface.
type MockBrowseEventService struct {
	ctrl     *gomock.Controller
	recorder *MockBrowseEventServiceMockRecorder
}

// MockBrowseEventServiceMockRecorder is the mock recorder for MockBrowseEventService.
type MockBrowseEventServiceMockRecorder struct {
	mock *MockBrowseEventService
}

// NewMockBrowseEventService creates a new mock instance.
func NewMockBrowseEventService(ctrl *gomock.Controller) *MockBrowseEventService {
	mock := &MockBrowseEventService{ctrl: ctrl}
	mock.recorder = &MockBrowseEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowseEventService) EXPECT() *MockBrowseEventServiceMockRecorder {
	return m.recorder
}

// CaptureEvent mocks base method.
func (m *MockBrowseEventService) CaptureEvent(arg0 context.Context, arg1 string, arg2 time.Time, arg3 career1.EventCaptureMode, arg4 ...service.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CaptureEvent", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CaptureEvent indicates an expected call of CaptureEvent.
func (mr *MockBrowseEventServiceMockRecorder) CaptureEvent(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaptureEvent", reflect.TypeOf((*MockBrowseEventService)(nil).CaptureEvent), varargs...)
}

// DeleteEvent mocks base method.
func (m *MockBrowseEventService) DeleteEvent(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockBrowseEventServiceMockRecorder) DeleteEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockBrowseEventService)(nil).DeleteEvent), arg0, arg1)
}

// GetSkillsForEvent mocks base method.
func (m *MockBrowseEventService) GetSkillsForEvent(arg0 context.Context, arg1 string) ([]*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkillsForEvent", arg0, arg1)
	ret0, _ := ret[0].([]*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkillsForEvent indicates an expected call of GetSkillsForEvent.
func (mr *MockBrowseEventServiceMockRecorder) GetSkillsForEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkillsForEvent", reflect.TypeOf((*MockBrowseEventService)(nil).GetSkillsForEvent), arg0, arg1)
}

// ListEvents mocks base method.
func (m *MockBrowseEventService) ListEvents(arg0 context.Context, arg1 *career0.EventListFilters) ([]*career.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1)
	ret0, _ := ret[0].([]*career.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockBrowseEventServiceMockRecorder) ListEvents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockBrowseEventService)(nil).ListEvents), arg0, arg1)
}

// UpdateEventMetadata mocks base method.
func (m *MockBrowseEventService) UpdateEventMetadata(arg0 context.Context, arg1 *career.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventMetadata", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEventMetadata indicates an expected call of UpdateEventMetadata.
func (mr *MockBrowseEventServiceMockRecorder) UpdateEventMetadata(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventMetadata", reflect.TypeOf((*MockBrowseEventService)(nil).UpdateEventMetadata), arg0, arg1)
}
