// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/tui/intents/browsetimeline (interfaces: EventCRUDService,EventSkillCreator)

// Package mockintent is a generated GoMock package.
package mockintent

import (
	context "context"
	reflect "reflect"
	time "time"

	service "github.com/baphled/kariya/internal/cli/service"
	career "github.com/baphled/kariya/internal/domain/career"
	career0 "github.com/baphled/kariya/internal/repository/career"
	career1 "github.com/baphled/kariya/internal/service/career"
	gomock "github.com/golang/mock/gomock"
)

// MockBrowseEventCRUDService is a mock of EventCRUDService interface.
type MockBrowseEventCRUDService struct {
	ctrl     *gomock.Controller
	recorder *MockBrowseEventCRUDServiceMockRecorder
}

// MockBrowseEventCRUDServiceMockRecorder is the mock recorder for MockBrowseEventCRUDService.
type MockBrowseEventCRUDServiceMockRecorder struct {
	mock *MockBrowseEventCRUDService
}

// NewMockBrowseEventCRUDService creates a new mock instance.
func NewMockBrowseEventCRUDService(ctrl *gomock.Controller) *MockBrowseEventCRUDService {
	mock := &MockBrowseEventCRUDService{ctrl: ctrl}
	mock.recorder = &MockBrowseEventCRUDServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowseEventCRUDService) EXPECT() *MockBrowseEventCRUDServiceMockRecorder {
	return m.recorder
}

// CaptureEvent mocks base method.
func (m *MockBrowseEventCRUDService) CaptureEvent(arg0 context.Context, arg1 string, arg2 time.Time, arg3 career1.EventCaptureMode, arg4 ...service.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CaptureEvent", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CaptureEvent indicates an expected call of CaptureEvent.
func (mr *MockBrowseEventCRUDServiceMockRecorder) CaptureEvent(arg0, arg1, arg2, arg3 interface{}, arg4 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaptureEvent", reflect.TypeOf((*MockBrowseEventCRUDService)(nil).CaptureEvent), varargs...)
}

// DeleteEvent mocks base method.
func (m *MockBrowseEventCRUDService) DeleteEvent(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockBrowseEventCRUDServiceMockRecorder) DeleteEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockBrowseEventCRUDService)(nil).DeleteEvent), arg0, arg1)
}

// ListEvents mocks base method.
func (m *MockBrowseEventCRUDService) ListEvents(arg0 context.Context, arg1 *career0.EventListFilters) ([]*career.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1)
	ret0, _ := ret[0].([]*career.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockBrowseEventCRUDServiceMockRecorder) ListEvents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockBrowseEventCRUDService)(nil).ListEvents), arg0, arg1)
}

// UpdateEventMetadata mocks base method.
func (m *MockBrowseEventCRUDService) UpdateEventMetadata(arg0 context.Context, arg1 *career.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEventMetadata", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEventMetadata indicates an expected call of UpdateEventMetadata.
func (mr *MockBrowseEventCRUDServiceMockRecorder) UpdateEventMetadata(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEventMetadata", reflect.TypeOf((*MockBrowseEventCRUDService)(nil).UpdateEventMetadata), arg0, arg1)
}

// MockBrowseEventSkillCreator is a mock of EventSkillCreator interface.
type MockBrowseEventSkillCreator struct {
	ctrl     *gomock.Controller
	recorder *MockBrowseEventSkillCreatorMockRecorder
}

// MockBrowseEventSkillCreatorMockRecorder is the mock recorder for MockBrowseEventSkillCreator.
type MockBrowseEventSkillCreatorMockRecorder struct {
	mock *MockBrowseEventSkillCreator
}

// NewMockBrowseEventSkillCreator creates a new mock instance.
func NewMockBrowseEventSkillCreator(ctrl *gomock.Controller) *MockBrowseEventSkillCreator {
	mock := &MockBrowseEventSkillCreator{ctrl: ctrl}
	mock.recorder = &MockBrowseEventSkillCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowseEventSkillCreator) EXPECT() *MockBrowseEventSkillCreatorMockRecorder {
	return m.recorder
}

// GetSkillsForEvent mocks base method.
func (m *MockBrowseEventSkillCreator) GetSkillsForEvent(arg0 context.Context, arg1 string) ([]*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkillsForEvent", arg0, arg1)
	ret0, _ := ret[0].([]*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkillsForEvent indicates an expected call of GetSkillsForEvent.
func (mr *MockBrowseEventSkillCreatorMockRecorder) GetSkillsForEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkillsForEvent", reflect.TypeOf((*MockBrowseEventSkillCreator)(nil).GetSkillsForEvent), arg0, arg1)
}

// LinkSkillToEvent mocks base method.
func (m *MockBrowseEventSkillCreator) LinkSkillToEvent(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkSkillToEvent", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkSkillToEvent indicates an expected call of LinkSkillToEvent.
func (mr *MockBrowseEventSkillCreatorMockRecorder) LinkSkillToEvent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkSkillToEvent", reflect.TypeOf((*MockBrowseEventSkillCreator)(nil).LinkSkillToEvent), arg0, arg1, arg2)
}

// ListAllSkills mocks base method.
func (m *MockBrowseEventSkillCreator) ListAllSkills(arg0 context.Context) ([]*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllSkills", arg0)
	ret0, _ := ret[0].([]*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllSkills indicates an expected call of ListAllSkills.
func (mr *MockBrowseEventSkillCreatorMockRecorder) ListAllSkills(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllSkills", reflect.TypeOf((*MockBrowseEventSkillCreator)(nil).ListAllSkills), arg0)
}

// UnlinkSkillFromEvent mocks base method.
func (m *MockBrowseEventSkillCreator) UnlinkSkillFromEvent(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkSkillFromEvent", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkSkillFromEvent indicates an expected call of UnlinkSkillFromEvent.
func (mr *MockBrowseEventSkillCreatorMockRecorder) UnlinkSkillFromEvent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkSkillFromEvent", reflect.TypeOf((*MockBrowseEventSkillCreator)(nil).UnlinkSkillFromEvent), arg0, arg1, arg2)
}
