// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/cli/intents/burst_management (interfaces: BurstService)

// Package mockintent is a generated GoMock package.
package mockintent

import (
	context "context"
	reflect "reflect"

	career "github.com/baphled/kariya/internal/domain/career"
	career0 "github.com/baphled/kariya/internal/repository/career"
	burstfact "github.com/baphled/kariya/internal/service/career/burstfact"
	gomock "github.com/golang/mock/gomock"
)

// MockBurstService is a mock of BurstService interface.
type MockBurstService struct {
	ctrl     *gomock.Controller
	recorder *MockBurstServiceMockRecorder
}

// MockBurstServiceMockRecorder is the mock recorder for MockBurstService.
type MockBurstServiceMockRecorder struct {
	mock *MockBurstService
}

// NewMockBurstService creates a new mock instance.
func NewMockBurstService(ctrl *gomock.Controller) *MockBurstService {
	mock := &MockBurstService{ctrl: ctrl}
	mock.recorder = &MockBurstServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBurstService) EXPECT() *MockBurstServiceMockRecorder {
	return m.recorder
}

// ConfirmBurst mocks base method.
func (m *MockBurstService) ConfirmBurst(arg0 context.Context, arg1 *career.Burst) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmBurst", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmBurst indicates an expected call of ConfirmBurst.
func (mr *MockBurstServiceMockRecorder) ConfirmBurst(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmBurst", reflect.TypeOf((*MockBurstService)(nil).ConfirmBurst), arg0, arg1)
}

// ExtractFactsFromBurst mocks base method.
func (m *MockBurstService) ExtractFactsFromBurst(arg0 context.Context, arg1 *career.Burst) ([]career.Fact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFactsFromBurst", arg0, arg1)
	ret0, _ := ret[0].([]career.Fact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFactsFromBurst indicates an expected call of ExtractFactsFromBurst.
func (mr *MockBurstServiceMockRecorder) ExtractFactsFromBurst(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFactsFromBurst", reflect.TypeOf((*MockBurstService)(nil).ExtractFactsFromBurst), arg0, arg1)
}

// GetEventByID mocks base method.
func (m *MockBurstService) GetEventByID(arg0 context.Context, arg1 string) (*career.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventByID", arg0, arg1)
	ret0, _ := ret[0].(*career.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventByID indicates an expected call of GetEventByID.
func (mr *MockBurstServiceMockRecorder) GetEventByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventByID", reflect.TypeOf((*MockBurstService)(nil).GetEventByID), arg0, arg1)
}

// GetFactsBySourceBurstID mocks base method.
func (m *MockBurstService) GetFactsBySourceBurstID(arg0 context.Context, arg1 string) ([]*career.Fact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFactsBySourceBurstID", arg0, arg1)
	ret0, _ := ret[0].([]*career.Fact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFactsBySourceBurstID indicates an expected call of GetFactsBySourceBurstID.
func (mr *MockBurstServiceMockRecorder) GetFactsBySourceBurstID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFactsBySourceBurstID", reflect.TypeOf((*MockBurstService)(nil).GetFactsBySourceBurstID), arg0, arg1)
}

// ListEvents mocks base method.
func (m *MockBurstService) ListEvents(arg0 context.Context, arg1 career0.EventListFilters) ([]*career.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1)
	ret0, _ := ret[0].([]*career.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockBurstServiceMockRecorder) ListEvents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockBurstService)(nil).ListEvents), arg0, arg1)
}

// SaveFact mocks base method.
func (m *MockBurstService) SaveFact(arg0 context.Context, arg1 *career.Fact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFact", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFact indicates an expected call of SaveFact.
func (mr *MockBurstServiceMockRecorder) SaveFact(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFact", reflect.TypeOf((*MockBurstService)(nil).SaveFact), arg0, arg1)
}

// SuggestBursts mocks base method.
func (m *MockBurstService) SuggestBursts(arg0 context.Context, arg1 []string) ([]burstfact.BurstSuggestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestBursts", arg0, arg1)
	ret0, _ := ret[0].([]burstfact.BurstSuggestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestBursts indicates an expected call of SuggestBursts.
func (mr *MockBurstServiceMockRecorder) SuggestBursts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestBursts", reflect.TypeOf((*MockBurstService)(nil).SuggestBursts), arg0, arg1)
}
