// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/cli/intents/burst_management (interfaces: SkillInferenceService)

// Package mockintent is a generated GoMock package.
package mockintent

import (
	context "context"
	reflect "reflect"

	career "github.com/baphled/kariya/internal/domain/career"
	skillinference "github.com/baphled/kariya/internal/service/career/skillinference"
	gomock "github.com/golang/mock/gomock"
)

// MockBurstSkillInferenceService is a mock of SkillInferenceService interface.
type MockBurstSkillInferenceService struct {
	ctrl     *gomock.Controller
	recorder *MockBurstSkillInferenceServiceMockRecorder
}

// MockBurstSkillInferenceServiceMockRecorder is the mock recorder for MockBurstSkillInferenceService.
type MockBurstSkillInferenceServiceMockRecorder struct {
	mock *MockBurstSkillInferenceService
}

// NewMockBurstSkillInferenceService creates a new mock instance.
func NewMockBurstSkillInferenceService(ctrl *gomock.Controller) *MockBurstSkillInferenceService {
	mock := &MockBurstSkillInferenceService{ctrl: ctrl}
	mock.recorder = &MockBurstSkillInferenceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBurstSkillInferenceService) EXPECT() *MockBurstSkillInferenceServiceMockRecorder {
	return m.recorder
}

// CreateSkillsFromSuggestions mocks base method.
func (m *MockBurstSkillInferenceService) CreateSkillsFromSuggestions(arg0 context.Context, arg1 []skillinference.SkillSuggestion) ([]*career.Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSkillsFromSuggestions", arg0, arg1)
	ret0, _ := ret[0].([]*career.Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSkillsFromSuggestions indicates an expected call of CreateSkillsFromSuggestions.
func (mr *MockBurstSkillInferenceServiceMockRecorder) CreateSkillsFromSuggestions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSkillsFromSuggestions", reflect.TypeOf((*MockBurstSkillInferenceService)(nil).CreateSkillsFromSuggestions), arg0, arg1)
}

// InferSkillsFromEvents mocks base method.
func (m *MockBurstSkillInferenceService) InferSkillsFromEvents(arg0 context.Context, arg1 []*career.Event) (*skillinference.InferenceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InferSkillsFromEvents", arg0, arg1)
	ret0, _ := ret[0].(*skillinference.InferenceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InferSkillsFromEvents indicates an expected call of InferSkillsFromEvents.
func (mr *MockBurstSkillInferenceServiceMockRecorder) InferSkillsFromEvents(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InferSkillsFromEvents", reflect.TypeOf((*MockBurstSkillInferenceService)(nil).InferSkillsFromEvents), arg0, arg1)
}
