// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/cli/intents/captureevent (interfaces: EventService)

// Package mockintent is a generated GoMock package.
package mockintent

import (
	reflect "reflect"

	service "github.com/baphled/kariya/internal/cli/service"
	career "github.com/baphled/kariya/internal/service/career"
	gomock "github.com/golang/mock/gomock"
)

// MockCaptureEventService is a mock of EventService interface.
type MockCaptureEventService struct {
	ctrl     *gomock.Controller
	recorder *MockCaptureEventServiceMockRecorder
}

// MockCaptureEventServiceMockRecorder is the mock recorder for MockCaptureEventService.
type MockCaptureEventServiceMockRecorder struct {
	mock *MockCaptureEventService
}

// NewMockCaptureEventService creates a new mock instance.
func NewMockCaptureEventService(ctrl *gomock.Controller) *MockCaptureEventService {
	mock := &MockCaptureEventService{ctrl: ctrl}
	mock.recorder = &MockCaptureEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaptureEventService) EXPECT() *MockCaptureEventServiceMockRecorder {
	return m.recorder
}

// GetCLIService mocks base method.
func (m *MockCaptureEventService) GetCLIService() *service.CLIEventService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCLIService")
	ret0, _ := ret[0].(*service.CLIEventService)
	return ret0
}

// GetCLIService indicates an expected call of GetCLIService.
func (mr *MockCaptureEventServiceMockRecorder) GetCLIService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCLIService", reflect.TypeOf((*MockCaptureEventService)(nil).GetCLIService))
}

// GetCareerService mocks base method.
func (m *MockCaptureEventService) GetCareerService() *career.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCareerService")
	ret0, _ := ret[0].(*career.Service)
	return ret0
}

// GetCareerService indicates an expected call of GetCareerService.
func (mr *MockCaptureEventServiceMockRecorder) GetCareerService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCareerService", reflect.TypeOf((*MockCaptureEventService)(nil).GetCareerService))
}
