// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baphled/kariya/internal/tui/intents/generatecv (interfaces: CVExporter)

// Package mockintent is a generated GoMock package.
package mockintent

import (
	context "context"
	reflect "reflect"

	config "github.com/baphled/kariya/internal/config"
	career "github.com/baphled/kariya/internal/domain/career"
	cv "github.com/baphled/kariya/internal/service/career/cv"
	gomock "github.com/golang/mock/gomock"
)

// MockCVExporter is a mock of CVExporter interface.
type MockCVExporter struct {
	ctrl     *gomock.Controller
	recorder *MockCVExporterMockRecorder
}

// MockCVExporterMockRecorder is the mock recorder for MockCVExporter.
type MockCVExporterMockRecorder struct {
	mock *MockCVExporter
}

// NewMockCVExporter creates a new mock instance.
func NewMockCVExporter(ctrl *gomock.Controller) *MockCVExporter {
	mock := &MockCVExporter{ctrl: ctrl}
	mock.recorder = &MockCVExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCVExporter) EXPECT() *MockCVExporterMockRecorder {
	return m.recorder
}

// CopyToClipboard mocks base method.
func (m *MockCVExporter) CopyToClipboard(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyToClipboard", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyToClipboard indicates an expected call of CopyToClipboard.
func (mr *MockCVExporterMockRecorder) CopyToClipboard(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyToClipboard", reflect.TypeOf((*MockCVExporter)(nil).CopyToClipboard), arg0, arg1)
}

// ExportToMarkdown mocks base method.
func (m *MockCVExporter) ExportToMarkdown(arg0 context.Context, arg1 *career.CVView, arg2 []*career.CVSection, arg3 map[string][]*career.CVBullet) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportToMarkdown", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportToMarkdown indicates an expected call of ExportToMarkdown.
func (mr *MockCVExporterMockRecorder) ExportToMarkdown(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportToMarkdown", reflect.TypeOf((*MockCVExporter)(nil).ExportToMarkdown), arg0, arg1, arg2, arg3)
}

// ExportToText mocks base method.
func (m *MockCVExporter) ExportToText(arg0 context.Context, arg1 *career.CVView, arg2 []*career.CVSection, arg3 map[string][]*career.CVBullet) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportToText", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportToText indicates an expected call of ExportToText.
func (mr *MockCVExporterMockRecorder) ExportToText(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportToText", reflect.TypeOf((*MockCVExporter)(nil).ExportToText), arg0, arg1, arg2, arg3)
}

// ExportToYAML mocks base method.
func (m *MockCVExporter) ExportToYAML(arg0 context.Context, arg1 *career.CVView, arg2 []*career.CVSection, arg3 *config.ProfileConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportToYAML", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportToYAML indicates an expected call of ExportToYAML.
func (mr *MockCVExporterMockRecorder) ExportToYAML(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportToYAML", reflect.TypeOf((*MockCVExporter)(nil).ExportToYAML), arg0, arg1, arg2, arg3)
}

// SaveToFile mocks base method.
func (m *MockCVExporter) SaveToFile(arg0 context.Context, arg1 string, arg2 cv.ExportFormat, arg3 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToFile", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveToFile indicates an expected call of SaveToFile.
func (mr *MockCVExporterMockRecorder) SaveToFile(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToFile", reflect.TypeOf((*MockCVExporter)(nil).SaveToFile), arg0, arg1, arg2, arg3)
}
