// Package mockintent provides GoMock-generated test doubles for intent-layer interfaces.
//
// # Overview
//
// All mocks in this package are auto-generated by mockgen from interfaces
// defined in internal/tui/intents/. Do not edit generated files manually.
//
// # Generation
//
// Regenerate all mocks:
//
//	make generate-mocks
//
// Or generate only intent mocks:
//
//	go generate ./internal/tui/intents/...
//
// # Usage
//
//	import mockintent "github.com/baphled/kariya/internal/testutil/mocks/intent"
//
//	ctrl := gomock.NewController(t)
//	mockSvc := mockintent.NewMockBurstService(ctrl)
//	mockSvc.EXPECT().ListEvents(gomock.Any(), gomock.Any()).Return(testEvents, nil)
package mockintent
